### ISSUE TITLE
Issue when running mobilehead.py

### ISSUE THREAD

**Issue by tctx79** [KR0SIV/op25mobileControlHead#3]
I assume you just run the mobilehead.py command from command prompt?  I am running Windows 10.
As the missing dependencies came up I did pip installs for each of them and re-ran the mobilehead.py command.

I am now getting an error that states:

import serial.tools.list_ports
ModuleNotFoundError: No module named 'serial.tools'

I did a pip install for serial.  A pip install for serial.tools throws an error. Any thoughts?

**Comment by jacygamer** [comment]
Hi I had the same problem but figured out to install serial.tools via pip is 'serial-tool' for pyserial
as for line 2016 'gpssystemOptions' is needing four arguments an is only getting three, the third option is missing the initial state of whether the gps is enabled or disabled at runtime needs 'value' "True" or "False" before '*systems' 

as for line 2400 "locations.tsv" just needs to be an empty tsv file or your talkgroup file used with the OP25 program and the path needs to be edited as you figured out

**Comment by KR0SIV** [comment]
This is a bug due to development occurring primarily within windows for testing purposes.
A kivy port is in the works to resolve these issues as TKInter isn't going to work long-term for mobile application.

**Comment by killertez** [comment]
sudo python3 mobilehead.py
playsound is relying on another python subprocess. Please use `pip install pygobject` if you want playsound to run more efficiently.
Client is not authorized to connect to ServerClient is not authorized to connect to ServerTraceback (most recent call last):
  File "/home/pi/op25mobileControlHead/mobilehead.py", line 330, in <module>
    main_window = Tk()
  File "/usr/lib/python3.9/tkinter/__init__.py", line 2270, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display ":2.0"




can someone please help me with this problem

**Comment by killertez** [comment]
UPDATE:

sudo python3 mobilehead.py
Client is not authorized to connect to ServerClient is not authorized to connect to ServerTraceback (most recent call last):
  File "/home/pi/op25mobileControlHead/mobilehead.py", line 330, in <module>
    main_window = Tk()
  File "/usr/lib/python3.9/tkinter/__init__.py", line 2270, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display ":2.0"
